%% data plot
figure('color',[1 1 1]);
c = 'rg';
for i_novelty = 1:numbers.nb_novelties
    subplot(1,numbers.nb_novelties,i_novelty);
    hold on;
    this_subdata = nan(numbers.nb_subjects,numbers.nb_trials);
    this_modeldata = nan(numbers.nb_subjects,numbers.nb_trials);
    this_optdata = nan(numbers.nb_subjects,numbers.nb_trials);
    for i_subject = 1:numbers.nb_subjects
        % subject
        this_subdata(i_subject,:) = sdata.subdata(...
                                                i_subject,...
                                                i_novelty,...
                                                find(numbers.u_propabs == sdata.minpropabs(i_subject,i_novelty)),...
                                                find(numbers.u_propang == sdata.minpropang(i_subject,i_novelty)),...
                                                find(numbers.u_thresh  == sdata.minthresh(i_subject,i_novelty)),...
                                                :...
                                            );
        % model
        this_modeldata(i_subject,:) = sdata.moddata(...
                                                i_subject,...
                                                i_novelty,...
                                                find(numbers.u_propabs == sdata.minpropabs(i_subject,i_novelty)),...
                                                find(numbers.u_propang == sdata.minpropang(i_subject,i_novelty)),...
                                                find(numbers.u_thresh  == sdata.minthresh(i_subject,i_novelty)),...
                                                :...
                                            );
        % optimal
        this_optdata(i_subject,:) = sdata.moddata(...
                                                i_subject,...
                                                i_novelty,...
                                                1,...
                                                numbers.nb_propangs,...
                                                1,...
                                                :...
                                            );
    end
    plot(squeeze(mean(this_subdata)), 'o','markerfacecolor','k','markeredgecolor','k','markersize',10);
    plot(squeeze(mean(this_modeldata)),'linewidth',2,'linestyle','-','color',c(i_novelty));
    plot(squeeze(mean(this_optdata)),'linewidth',2,'linestyle','-.','color','k');
    ylim([0 1]);
    xlim([1 numbers.nb_trials]);
    set(gca,'fontsize',16,'fontname','Arial');
    sdata.plots.sub_target{i_novelty} = this_subdata;
    sdata.plots.mod_target{i_novelty} = this_modeldata;
    sdata.plots.opt_target{i_novelty} = this_optdata;
end
% clean
clearvars -except sdata numbers;

%% other plot
figure('color',[1 1 1]);
c = 'rg';
for i_novelty = 1:numbers.nb_novelties
    subplot(1,numbers.nb_novelties,i_novelty);
    hold on;
    this_subdata = nan(numbers.nb_subjects,numbers.nb_trials);
    this_modeldata = nan(numbers.nb_subjects,numbers.nb_trials);
    this_optdata = nan(numbers.nb_subjects,numbers.nb_trials);
    for i_subject = 1:numbers.nb_subjects
        % subject
        this_subdata(i_subject,:) = sdata.subother(...
                                                i_subject,...
                                                i_novelty,...
                                                find(numbers.u_propabs == sdata.minpropabs(i_subject,i_novelty)),...
                                                find(numbers.u_propang == sdata.minpropang(i_subject,i_novelty)),...
                                                find(numbers.u_thresh  == sdata.minthresh(i_subject,i_novelty)),...
                                                :...
                                            );
        % model
        this_modeldata(i_subject,:) = sdata.modother(...
                                                i_subject,...
                                                i_novelty,...
                                                find(numbers.u_propabs == sdata.minpropabs(i_subject,i_novelty)),...
                                                find(numbers.u_propang == sdata.minpropang(i_subject,i_novelty)),...
                                                find(numbers.u_thresh  == sdata.minthresh(i_subject,i_novelty)),...
                                                :...
                                            );
        % optimal
        this_optdata(i_subject,:) = sdata.modother(...
                                                i_subject,...
                                                i_novelty,...
                                                1,...
                                                numbers.nb_propangs,...
                                                1,...
                                                :...
                                            );
    end
    plot(squeeze(mean(this_subdata)), 'o','markerfacecolor','k','markeredgecolor','k','markersize',10);
    plot(squeeze(mean(this_modeldata)),'linewidth',2,'linestyle','-','color',c(i_novelty));
    plot(squeeze(mean(this_optdata)),'linewidth',2,'linestyle','-.','color','k');
    ylim([0 1]);
    xlim([1 numbers.nb_trials]);
    set(gca,'fontsize',16,'fontname','Arial');
    sdata.plots.sub_perfor{i_novelty} = this_subdata;
    sdata.plots.mod_perfor{i_novelty} = this_modeldata;
    sdata.plots.opt_perfor{i_novelty} = this_optdata;
end
% clean
clearvars -except sdata numbers;
